apiVersion: apps/v1
kind: Deployment
metadata:
  name: amy-app-deploy
  labels:
    app: amy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amy-app
  template:
    metadata:
      labels:
        app: amy-app
    spec:
      containers:
      - name: amy-app
        image: gcr.io/lbg-210322/amy-image:v61
        ports:
        - containerPort: 5000
